// ===================================================
// FUSION MUSHROOM BARS EU - API & SERVER ACTION INVENTORY
// Formal Production Security Specification & Access Control Reference
// ===================================================

export type SecurityTier = 'PUBLIC' | 'CUSTOMER' | 'ADMIN' | 'FINANCE' | 'SYSTEM';

export interface ApiInventoryEntry {
  identifier: string;
  type: 'API_ROUTE' | 'SERVER_ACTION';
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'ACTION';
  route: string;
  purpose: string;
  authentication: 'NONE' | 'SESSION_COOKIE' | 'BEARER_TOKEN' | 'LOOKUP_TOKEN' | 'ROLE_BASED';
  authorization: string;
  tier: SecurityTier;
  inputSchema: string;
  outputDescription: string;
  rateLimit: string;
  databaseAccess: 'READ' | 'WRITE' | 'READ_WRITE' | 'NONE';
  sensitiveInformationExposed: string;
}

export const API_SECURITY_INVENTORY: ApiInventoryEntry[] = [
  // ----------------------------------------------------
  // PUBLIC MARKETING & SHOP ENDPOINTS
  // ----------------------------------------------------
  {
    identifier: 'HEALTH_CHECK',
    type: 'API_ROUTE',
    method: 'GET',
    route: '/api/health',
    purpose: 'Container and database liveness and readiness probe for Cloud Run / Vercel',
    authentication: 'NONE',
    authorization: 'Public unauthenticated',
    tier: 'PUBLIC',
    inputSchema: 'None',
    outputDescription: 'JSON { status: "ok", timestamp: ISO8601, database: boolean }',
    rateLimit: '120 req/min',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'None. Only generic status and system timestamps.',
  },
  {
    identifier: 'CURRENCY_RATES',
    type: 'API_ROUTE',
    method: 'GET',
    route: '/api/currency',
    purpose: 'Returns public currency exchange rates and base settlement currencies (EUR/GBP)',
    authentication: 'NONE',
    authorization: 'Public unauthenticated',
    tier: 'PUBLIC',
    inputSchema: 'None',
    outputDescription: 'JSON exchange rate multipliers',
    rateLimit: '60 req/min',
    databaseAccess: 'NONE',
    sensitiveInformationExposed: 'None',
  },
  {
    identifier: 'CART_CALCULATION',
    type: 'API_ROUTE',
    method: 'POST',
    route: '/api/cart/calculate',
    purpose: 'Authoritative server-side cart pricing and subtotal calculation',
    authentication: 'NONE',
    authorization: 'Public unauthenticated',
    tier: 'PUBLIC',
    inputSchema: 'cartCalculationRequestSchema { items, currency, couponCode? }',
    outputDescription: 'JSON CartCalculationResult (subtotal, discounts, line totals in minor units)',
    rateLimit: '60 req/min',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'None',
  },
  {
    identifier: 'CHECKOUT_QUOTE',
    type: 'API_ROUTE',
    method: 'POST',
    route: '/api/checkout/quote',
    purpose: 'Calculates authoritative shipping fee, subtotal, and total quote for destination',
    authentication: 'NONE',
    authorization: 'Public unauthenticated',
    tier: 'PUBLIC',
    inputSchema: 'JSON { items, currency, countryCode, shippingMethod, couponCode? }',
    outputDescription: 'JSON OrderPricingQuote with shipping calculation',
    rateLimit: '30 req/min',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'None. Internal hub assignment is not exposed.',
  },
  {
    identifier: 'CREATE_ORDER_API',
    type: 'API_ROUTE',
    method: 'POST',
    route: '/api/orders',
    purpose: 'REST API entry point for order creation',
    authentication: 'NONE',
    authorization: 'Public / Guest / Authenticated Customer',
    tier: 'PUBLIC',
    inputSchema: 'createOrderSchema',
    outputDescription: 'JSON 201 Created with order summary and payment instructions',
    rateLimit: '15 req/min per IP',
    databaseAccess: 'READ_WRITE',
    sensitiveInformationExposed: 'Selected payment instructions for this specific order only.',
  },

  // ----------------------------------------------------
  // SERVER ACTIONS: COMMERCE & CHECKOUT
  // ----------------------------------------------------
  {
    identifier: 'CREATE_ORDER_ACTION',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'createOrderAction (src/actions/orders.ts)',
    purpose: 'Atomically creates order, reserves inventory, generates payment instructions',
    authentication: 'NONE',
    authorization: 'Guest or Customer Session',
    tier: 'PUBLIC',
    inputSchema: 'createOrderSchema { items, currency, shippingAddress, shippingMethodCode, paymentMethodCode, couponCode? }',
    outputDescription: '{ success: true, data: { orderNumber, lookupToken, paymentInstructions, ... } }',
    rateLimit: '10 orders / 10m per IP',
    databaseAccess: 'READ_WRITE',
    sensitiveInformationExposed: 'Only payment instructions for the selected method. No admin credentials.',
  },
  {
    identifier: 'LOOKUP_ORDER_ACTION',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'lookupOrderAction (src/actions/orders.ts)',
    purpose: 'Secure order status lookup without exposing carrier tracking or internal hub mechanics',
    authentication: 'LOOKUP_TOKEN',
    authorization: 'Signed lookup token OR matching orderNumber + guest email (Dual-Factor)',
    tier: 'PUBLIC',
    inputSchema: '{ token?: string, orderNumber?: string, email?: string }',
    outputDescription: '{ success: true, order: SafeOrderRecord }',
    rateLimit: '20 requests / 10m (rate-limited against probing)',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'Customer shipping address and order status. Fulfilment hub and notes strictly redacted.',
  },

  // ----------------------------------------------------
  // SERVER ACTIONS: CUSTOMER ACCOUNTS & IDOR PROTECTED
  // ----------------------------------------------------
  {
    identifier: 'CUSTOMER_REGISTER',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'registerCustomerAction (src/actions/customer.ts)',
    purpose: 'Registers customer with bcrypt-hashed credentials and issues secure httpOnly cookie',
    authentication: 'NONE',
    authorization: 'Public unauthenticated',
    tier: 'PUBLIC',
    inputSchema: 'customerRegisterSchema { email, password, firstName, lastName, phone?, preferredLocale, preferredCurrency }',
    outputDescription: '{ success: true, customer: SanitizedCustomerProfile }',
    rateLimit: '5 registrations / hour per IP',
    databaseAccess: 'WRITE',
    sensitiveInformationExposed: 'None. Password hashed with 12 bcrypt rounds.',
  },
  {
    identifier: 'CUSTOMER_LOGIN',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'loginCustomerAction (src/actions/customer.ts)',
    purpose: 'Authenticates customer credentials, sets signed session cookie',
    authentication: 'NONE',
    authorization: 'Public unauthenticated',
    tier: 'PUBLIC',
    inputSchema: 'customerLoginSchema { email, password }',
    outputDescription: '{ success: true, customer: SanitizedCustomerProfile }',
    rateLimit: '10 attempts / 15m per IP/email',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'None',
  },
  {
    identifier: 'GET_CUSTOMER_ORDERS',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'getCustomerOrdersAction (src/actions/orders.ts)',
    purpose: 'Retrieves authenticated customer order history (IDOR protected)',
    authentication: 'SESSION_COOKIE',
    authorization: 'CUSTOMER (Strict session match: caller can only read own orders)',
    tier: 'CUSTOMER',
    inputSchema: 'Optional customerIdOrEmail (validated against session identity)',
    outputDescription: '{ success: true, orders: DbOrder[] }',
    rateLimit: '60 req/min',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'Customer personal order history. Barred from cross-customer access.',
  },
  {
    identifier: 'GET_CUSTOMER_ADDRESSES',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'getCustomerAddressesAction (src/actions/customer.ts)',
    purpose: 'Retrieves saved address book for authenticated customer',
    authentication: 'SESSION_COOKIE',
    authorization: 'CUSTOMER (Session-bound)',
    tier: 'CUSTOMER',
    inputSchema: 'None (bound to session.id)',
    outputDescription: '{ success: true, addresses: DbAddress[] }',
    rateLimit: '60 req/min',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'Saved customer delivery addresses.',
  },
  {
    identifier: 'SUBMIT_PAYMENT_PROOF',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'submitPaymentProofAction (src/actions/payments.ts)',
    purpose: 'Submits payment reference/TXID (IDOR protected: verifies session or lookup token)',
    authentication: 'SESSION_COOKIE',
    authorization: 'CUSTOMER or Verified Guest token',
    tier: 'CUSTOMER',
    inputSchema: 'paymentProofSubmissionSchema { orderId, referenceOrTxid, senderAccountName?, proofFileUrl?, lookupToken?, guestEmail? }',
    outputDescription: '{ success: true, message: string, status: "PAYMENT_SUBMITTED" }',
    rateLimit: '10 submissions / 15m per order',
    databaseAccess: 'WRITE',
    sensitiveInformationExposed: 'Logs transaction reference. Cross-customer submission strictly forbidden.',
  },

  // ----------------------------------------------------
  // FINANCE & ADMINISTRATION
  // ----------------------------------------------------
  {
    identifier: 'VERIFY_PAYMENT_STATUS',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'verifyPaymentStatusAction (src/actions/payments.ts)',
    purpose: 'Finance Desk verification advancing order from PAYMENT_SUBMITTED to PAYMENT_VERIFIED',
    authentication: 'ROLE_BASED',
    authorization: 'FINANCE_MANAGER, SUPER_ADMIN',
    tier: 'FINANCE',
    inputSchema: 'VerifyPaymentInput { orderId, targetStatus, actorRole, actorId, notes? }',
    outputDescription: '{ success: true, newStatus: "PAYMENT_VERIFIED" | "CANCELLED" }',
    rateLimit: '60 req/min',
    databaseAccess: 'WRITE',
    sensitiveInformationExposed: 'Administrative finance auditing notes (scrubbed of passwords/keys).',
  },
  {
    identifier: 'UPDATE_ORDER_STATUS_ADMIN',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'updateOrderStatusAdminAction (src/actions/orders.ts)',
    purpose: 'Administrative order lifecycle advancement (PROCESSING, SHIPPED, DELIVERED, CANCELLED)',
    authentication: 'ROLE_BASED',
    authorization: 'ORDER_MANAGER, SUPER_ADMIN',
    tier: 'ADMIN',
    inputSchema: 'orderStatusTransitionSchema { orderId, newStatus, actorRole, actorId, note?, trackingNumber?, carrierName? }',
    outputDescription: '{ success: true, order: DbOrder }',
    rateLimit: '60 req/min',
    databaseAccess: 'WRITE',
    sensitiveInformationExposed: 'Internal logistics status and fulfilment notes.',
  },
  {
    identifier: 'INVENTORY_ADJUSTMENT',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'adjustInventoryAction (src/actions/inventory.ts)',
    purpose: 'Warehouse restock, cycle counts, write-offs per European Fulfilment Hub (NL/ES/DE/FR)',
    authentication: 'ROLE_BASED',
    authorization: 'ORDER_MANAGER, SUPER_ADMIN',
    tier: 'ADMIN',
    inputSchema: 'inventoryAdjustmentSchema { variantId, hub, delta, reason }',
    outputDescription: '{ success: true, record: DbInventoryRecord }',
    rateLimit: '60 req/min',
    databaseAccess: 'WRITE',
    sensitiveInformationExposed: 'Warehouse stock levels and inventory movement records.',
  },
  {
    identifier: 'PRIVACY_EXPORT',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'exportCustomerDataAction (src/actions/privacy.ts)',
    purpose: 'GDPR Right of Access: machine-readable JSON data export',
    authentication: 'SESSION_COOKIE',
    authorization: 'CUSTOMER (Session-isolated)',
    tier: 'CUSTOMER',
    inputSchema: 'None (bound to caller session)',
    outputDescription: '{ success: true, exportData: CustomerDataExport }',
    rateLimit: '5 requests / day',
    databaseAccess: 'READ',
    sensitiveInformationExposed: 'Complete customer profile, addresses, order history, and consent logs.',
  },
  {
    identifier: 'PRIVACY_ACCOUNT_DELETION',
    type: 'SERVER_ACTION',
    method: 'ACTION',
    route: 'deleteCustomerAccountAction (src/actions/privacy.ts)',
    purpose: 'GDPR Right to Erasure: removes profile/addresses, anonymizes order PII',
    authentication: 'SESSION_COOKIE',
    authorization: 'CUSTOMER (Session-isolated)',
    tier: 'CUSTOMER',
    inputSchema: 'None (bound to caller session)',
    outputDescription: '{ success: true, message: string, anonymizedOrdersCount: number }',
    rateLimit: '1 request per session',
    databaseAccess: 'WRITE',
    sensitiveInformationExposed: 'None. PII is permanently removed.',
  },
];
